# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }: {
  awesome = {
    pname = "awesome";
    version = "8b1f8958b46b3e75618bc822d512bb4d449a89aa";
    src = fetchFromGitHub {
      owner = "awesomeWM";
      repo = "awesome";
      rev = "8b1f8958b46b3e75618bc822d512bb4d449a89aa";
      fetchSubmodules = false;
      sha256 = "sha256-ZGZ53IWfQfNU8q/hKexFpb/2mJyqtK5M9t9HrXoEJCg=";
    };
    date = "2024-03-23";
  };
}
