# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xivlauncher-rb = {
    pname = "xivlauncher-rb";
    version = "rb-v1.1.1.5";
    src = fetchFromGitHub {
      owner = "rankynbass";
      repo = "XIVLauncher.Core";
      rev = "rb-v1.1.1.5";
      fetchSubmodules = true;
      sha256 = "sha256-gGTxU80vvZTwUs/ulzrKikSBKIgB0VHFmVtwbOw7x38=";
    };
  };
}
