# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  skeuos-gtk-theme = {
    pname = "skeuos-gtk-theme";
    version = "20220629";
    src = fetchFromGitHub {
      owner = "daniruiz";
      repo = "skeuos-gtk";
      rev = "20220629";
      fetchSubmodules = false;
      sha256 = "sha256-cfVe6/M64wcf0WVbC+sGwsZjg9t70+5+lIf5j5fqz2w=";
    };
  };
}
