# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  decky-loader = {
    pname = "decky-loader";
    version = "v3.0.5";
    src = fetchurl {
      url = "https://github.com/SteamDeckHomebrew/decky-loader/releases/download/v3.0.5/PluginLoader";
      sha256 = "sha256-qLe9WP8MCsgPXAfh+hO+5F8bsXGVKD9JAqeTDECrp2E=";
    };
  };
}
