# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  decky-loader = {
    pname = "decky-loader";
    version = "v3.0.4";
    src = fetchurl {
      url = "https://github.com/SteamDeckHomebrew/decky-loader/releases/download/v3.0.4/PluginLoader";
      sha256 = "sha256-94pQL/fmpApP+suku4a/q7nTTf/zqVaT5rbVowEFYPY=";
    };
  };
}
