# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  discord-wal-theme = {
    pname = "discord-wal-theme";
    version = "efacc6cd2ee5ac2d3a16f51eb353804f86a58e5c";
    src = fetchFromGitHub {
      owner = "Gremious";
      repo = "discord-wal-theme-template";
      rev = "efacc6cd2ee5ac2d3a16f51eb353804f86a58e5c";
      fetchSubmodules = false;
      sha256 = "sha256-qfj14MmvmOmtrxS++eFv0ihN6iNH9fQzjyfujGgpS4I=";
    };
    date = "2024-04-16";
  };
}
