# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nos-wallpapers = {
    pname = "nos-wallpapers";
    version = "b335f9b78848eb8e92d5fc62f574d4a084642391";
    src = fetchFromGitHub {
      owner = "Naragiri";
      repo = "wallpapers";
      rev = "b335f9b78848eb8e92d5fc62f574d4a084642391";
      fetchSubmodules = false;
      sha256 = "sha256-ii2KR/zE6IvHDc2xgah2tNPU6+wkGiP3jhaC3sJeFIg=";
    };
    date = "2024-10-22";
  };
}
