# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  betterfox = {
    pname = "betterfox";
    version = "133.0";
    src = fetchFromGitHub {
      owner = "yokoffing";
      repo = "Betterfox";
      rev = "133.0";
      fetchSubmodules = false;
      sha256 = "sha256-Uu/a5t74GGvMIJP5tptqbiFiA+x2hw98irPdl8ynGoE=";
    };
  };
}
