# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  betterfox = {
    pname = "betterfox";
    version = "131.0";
    src = fetchFromGitHub {
      owner = "yokoffing";
      repo = "Betterfox";
      rev = "131.0";
      fetchSubmodules = false;
      sha256 = "sha256-CxPZxo9G44lRocNngjfwTBHSqL5dEJ5MNO5Iauoxp2Y=";
    };
  };
}
